services:
  ghost:
    image: ghost:6
    ports:
      - "2368:2368"
    environment:
      url: http://localhost:2368
      database__client: sqlite3
      database__connection__filename: /var/lib/ghost/content/data/ghost.db
      security__staffDeviceVerification: "false" # Disable login email verification code
    volumes:
      - ./content:/var/lib/ghost/content
      - ./theme:/var/lib/ghost/content/themes/dc-theme